### ISSUE TITLE
update bios

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#116]
Add Heather to about_bios.yml
![heathertayler](https://user-images.githubusercontent.com/2480577/47757573-5d59f780-dc7d-11e8-96e2-cc055218a178.png)
- name: Heather Talyer
    imagename: Heather Tayler
    title: Organizer
    bio: 
          Heather is a graphic designer who transitioned into web development.
          As a frontend developer she finds great satisfaction in bringing design
          concepts to life via writing beautiful, clean, responsive, and
          accessible code.
    image: /img/people/heathertayler.png
    sociallinks:
      - label: Twitter
        link: https://twitter.com/heatherhonie
        inconclass: fa fa-twitter
      - label: Website
        link: http://www.heathercancode.com/
        inconclass: fa fa-globe
      - label: LinkedIn
        link: https://www.linkedin.com/in/heatherdesigns
        inconclass: fa fa-linkedin-square

**Comment by kevinjonesevans** [comment]
Working on this
