### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#23]
In mobile browser the ../img/GDI_buttons_image3.jpg  scales awkward. 
![screenshot](https://cloud.githubusercontent.com/assets/2480577/19326585/255932b0-9099-11e6-9d68-2eab898ef33f.png)

**Comment by bryanbraun** [comment]
Just looking at this... given the merges referenced above, is this still an issue?

**Comment by kcjonesevans** [comment]
@bryanbraun yep it should be closed. Checkout the materials view issue though #31
