### ISSUE TITLE
Mobile View Navigation

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#24]
Someone want to make this look nicer? show the navigation in a list? Open to suggestions
![Screenshot](https://cloud.githubusercontent.com/assets/2480577/19326647/67293208-9099-11e6-8daa-86d9bb2540e0.png)

**Comment by kevinjonesevans** [comment]
What browser are you viewing this in?
The screenshot is the site in chrome when viewing as a Nexus 5X.
![screen shot 2016-10-30 at 9 35 02 pm](https://cloud.githubusercontent.com/assets/18356450/19841910/f2c83c8e-9ee8-11e6-8d2e-fa861baa1d96.png)

**Comment by k80bowman** [comment]
I think I fixed this one and then never closed the issue. I'm closing it now.
