### ISSUE TITLE
Add National's FAQ to Site

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#37]
https://www.girldevelopit.com/faq

- Add FAQ link in footer
- Create FAQ page matching national site

**Comment by AllenMay** [comment]
Do you want a similar 'accordion' for the content?
What GDI Dayton specific content do you want in the accordion?

**Comment by kcjonesevans** [comment]
Do you want a similar 'accordion' for the content? Yes
What GDI Dayton specific content do you want in the accordion? No copy is available at this time so please use the copy from the national site.

Also, If at all possible use yml to generate the accordions so that it is easier to add or remove FAQ in the future

**Comment by AllenMay** [comment]
RE: JS for FAQ
I could do one of the following. 
Which is most preferable:
- **Hot link** to the national page's JS file [tested and the accordion works]
(https://www.girldevelopit.com/assets/application-5ef7eb7cd51a9fbd2533623c4e3f8322.js)

- **Save a copy of the complete [application.js] file** from the national website
- **Save a local copy and trim it** down for only the accordion-specific JS functionality
- **Re-create the functionality with new JS**
