### ISSUE TITLE
Update profile for Kevin

### ISSUE THREAD

**Issue by saracope** [gdidayton/gdidayton.com#40]
New job.  Assigning K.C. because I don't see Kevin's username. 😁

**Comment by kevinjonesevans** [comment]
Here I am

**Comment by kcjonesevans** [comment]
yeah trying to add you to the repo to allow us to assign you

**Comment by saracope** [comment]
Can close?

**Comment by kevinjonesevans** [comment]
Sure, I think I would like to change my pic, but I can figure that out later.

**Comment by saracope** [comment]
👍
