### ISSUE TITLE
Compress images for better speed

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#55]
Properly formatting and compressing images can save many bytes of data.
[Optimize](https://developers.google.com/speed/docs/insights/OptimizeImages) the following images to reduce their size by 219.8KiB (58% reduction).

- Compressing http://gdidayton.com/img/events/event_code-coffee.jpeg could save 191.6KiB (84% reduction).
- Compressing http://gdidayton.com/img/events/event_html_css_refresher.png could save 16.3KiB (17% reduction).
- Compressing http://gdidayton.com/img/gdi-dayton-logo.png could save 12KiB (26% reduction).

**Comment by zastrow** [comment]
Oh, I am on this. I love optimizing images. 😍
