### ISSUE TITLE
Chapter Leaders and Staff on About Page re-work needed

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#57]
The [about page](https://github.com/gdidayton/gdidayton/blob/gh-pages/about.html) currently is modified in order to reflect the changes in our bios. Instead, using the sponsors and events as an example, we should have file with name, bios and pictures that generate the about page leadership and staff for easier updating

**Comment by spiraldancer** [comment]
taking

**Comment by spiraldancer** [comment]
did a pull request for this: about_page_rework

**Comment by spiraldancer** [comment]
I added all new requested changed but getting the social links to center on the page. The new css is based on the national site.

I will work on the centering next.

**Comment by spiraldancer** [comment]
fixed the centering of the social media icons.
