### ISSUE TITLE
Add links to bios

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#58]
add links to twitter, linkedin, website and mail on bios

**Comment by heatherdesigns** [comment]
👋  I'll take this one! 😄

**Comment by kcjonesevans** [comment]
How is this one going @heatherdesigns ? Do you need anything or are you stalking us all for the links?

**Comment by heatherdesigns** [comment]
I haven't started it yet........ But I claimed it because I thought it was something I could do. 😆 
And oh yes, I'll be stalking all of you!!! hahaha!!!
I'll work on it this weekend.

**Comment by saracope** [comment]
https://twitter.com/sarassassin
https://www.linkedin.com/in/saracope/
sarac@girldevelopit.com

Thanks!

**Comment by veldamart** [comment]
I will update the links to the bios
