### ISSUE TITLE
Change "Our Story"

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#59]
Need to update the copy under our story. First comment here with suggested text!

**Comment by spiraldancer** [comment]
The Dayton Girl Develop It chapter was founded June 2015. We meet regularly for Code & Coffee events. If its a weekend the meetup its at the Dayton Metro Library - Main. Weeknight events vary so look for the event posts and MeetUps. They are often at a Winan's or a coffee shop.
-------------
I would link "Girl Develop It" back to the nation's about page.
I remember folks talking about who was at the last code & coffee & chocolate that had been there from the beginning. You could also mention that the chapter started in 2015 with X-number of people.

**Comment by kcjonesevans** [comment]
The Dayton Girl Develop It chapter was founded June 2015 by Sara Cope. We meet regularly for Code & Coffee events and host workshops. Code & Coffee is an ongoing opportunity for you to practice your skills, meet new friends, and get help if you need it. Our workshops are available to help level up your skills.

**Comment by spiraldancer** [comment]
taking
