### ISSUE TITLE
Event cards distorted on hosted site but not in development

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#62]
In development the event cards looks very nice:
<img width="1483" alt="screen shot 2017-10-05 at 4 54 56 pm" src="https://user-images.githubusercontent.com/2480577/31252181-5de339e0-a9ee-11e7-9c5a-cde23d76be44.png">
But once loaded to github to be hosted they get a little weird:
<img width="1558" alt="screen shot 2017-10-05 at 4 56 20 pm" src="https://user-images.githubusercontent.com/2480577/31252190-668129fe-a9ee-11e7-8abc-e5a38258fc15.png">
Solution: Someone track down the CSS that is being weird and propose a solution

**Comment by zastrow** [comment]
I was wondering about that. I’m on it.
