### ISSUE TITLE
Accessibility: Link's need names

### ISSUE THREAD

**Issue by kcjonesevans** [gdidayton/gdidayton.com#66]
**Links do not have a discernable name.**
Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users. [Learn more](https://dequeuniversity.com/rules/axe/2.2/link-name?application=lighthouse).

**Failing Links**
The links generated using the _data/events.yml 
`<a href="https://www.meetup.com/preview/Girl-Develop-It-Dayton/events/243932091">`
Should read
`<a aria-label="Intermdiate JavaScript" href="https://www.meetup.com/preview/Girl-Develop-It-Dayton/events/243932091">`

**Comment by spiraldancer** [comment]
working on this

**Comment by kcjonesevans** [comment]
I can't accept your PR as is, it will generate errors, see the PR for comments on how to fix

**Comment by spiraldancer** [comment]
I had to create a new branch. resubmitted.
