### ISSUE TITLE
Re-style header hovers

### ISSUE THREAD

**Issue by k80bowman** [gdidayton/gdidayton.com#95]
![image](https://user-images.githubusercontent.com/12739849/40632741-4050d094-62b8-11e8-9553-d95c4ec059ce.png)

With the blue background on the hero image, it looks odd for the hovers on the header items to overlay it. We should re-think/re-design the hovers on these so they at the very least don't overlap the hero image.

**Comment by kcjonesevans** [comment]
National's website uses black with the weird overlap. Also the black outline goes to the top of the header. 

<img width="1019" alt="screen shot 2018-05-29 at 9 38 06 am" src="https://user-images.githubusercontent.com/2480577/40662348-16badefc-6324-11e8-9fd3-f7e382b6f480.png">

**Comment by kcjonesevans** [comment]
figured this out. it was in the tablet scss
